name: Deploy Flutter Web App

on:
  push:
    branches:
      - master # Deploys when code is pushed to 'master' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      # Step 3: Build the Flutter web project
      - run: flutter build web

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
